export const iconsData = [
  {
    "Style": "fas",
    "Name": "fa-angle-double-left",
    "React_name": "AngleDoubleLeftIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to navigate to the first page of a multi-page data set",
  },
  {
    "Style": "fas",
    "Name": "fa-angle-double-right",
    "React_name": "AngleDoubleRightIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to navigate to the last page of a multi-page data set",
  },
  {
    "Style": "fas",
    "Name": "fa-angle-down",
    "React_name": "AngleDownIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates expandable components such as accordions, progressive disclosures, or expandable lists are currently expanded. Clicking this will collapse the component.",
  },
  {
    "Style": "fas",
    "Name": "fa-angle-left",
    "React_name": "AngleLeftIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to navigate to the previous page of a multi-page data set",
  },
  {
    "Style": "fas",
    "Name": "fa-angle-right",
    "React_name": "AngleRightIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates expandable elements such as accordions, progressive disclosures, or expandable lists are currently collapsed. Clicking this will expand the element.",
    "Extra_context": "Also indicates the ability to navigate to the next page in a multipage data set."
  },
  {
    "Style": "fas",
    "Name": "fa-angle-up",
    "React_name": "AngleUpIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates expandable table rows (on mobile) are currently expanded. Clicking this will collapse the component.",
  },
  {
    "Style": "pficon",
    "Name": "pficon-ansible-tower",
    "React_name": "AnsibleTowerIcon",
    "Type": "Brand",
    "Contextual_usage": "Represents \"Ansible Tower\"",
  },
  {
    "Style": "fas",
    "Name": "fa-arrow-circle-down",
    "React_name": "ArrowCircleDownIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: an item (such as a VM) is down",
  },
  {
    "Style": "fas",
    "Name": "fa-arrow-circle-up",
    "React_name": "ArrowCircleUpIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: an item (such as a VM) is up",
    "Label": "Upgrade"
  },
  {
    "Style": "fas",
    "Name": "fa-arrows-alt-v",
    "React_name": "ArrowsAltVIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the availability of a sorting function in a table header",
  },
  {
    "Style": "fas",
    "Name": "fa-arrow-right",
    "React_name": "ArrowRightIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to take an action or navigate to another page. Is paired with text",
  },
  {
    "Style": "fas",
    "Name": "fa-balance-scale",
    "React_name": "BalanceScaleIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: an item needs rebalancing",
  },
  {
    "Style": "fas",
    "Name": "fa-ban",
    "React_name": "BanIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: an item is disabled, canceled, terminated or is not ready",
  },
  {
    "Style": "fas",
    "Name": "fa-bars",
    "React_name": "BarsIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to collapse a navigation menu",
  },
    {
      "Style": "fas",
      "Name": "fa-bell",
      "React_name": "BellIcon",
      "Type": "Framework",
      "Contextual_usage": "Indicates the ability to open a notification drawer.",
      "Label": "Notifications"
    },
    {
      "Style": "",
      "Name": "fa-bell (blue)",
      "React_name": "BellIcon",
      "Type": "Status",
      "Contextual_usage": "Represents status: default notification",
      color: 'var(--pf-v6-global--primary-color--100)',
    },
    {
      "Style": "pficon",
      "Name": "pficon-attention-bell",
      "React_name": "AttentionBellIcon",
      "Type": "Status",
      "Contextual_usage": "Represents status: attention",
    },
  {
    "Style": "fas",
    "Name": "fa-bug",
    "React_name": "BugIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: there is a bug present",
  },
  {
    "Style": "far",
    "Name": "fa-calendar-alt",
    "React_name": "OutlinedCalendarAltIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates a date picker function is available",
  },
  {
    "Style": "fas",
    "Name": "fa-caret-down",
    "React_name": "CaretDownIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to acces option panels for components like drop-downs, filters and page ranges",
  },
  {
    "Style": "fas",
    "Name": "fa-check",
    "React_name": "CheckIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: Indicates a switch toggle is in the enabled position",
  },
  {
    "Style": "fas",
    "Name": "fa-check-circle",
    "React_name": "CheckCircleIcon",
    "Type": ["Action","Status"],
    "Contextual_usage": "Indicates the ability to commit edited changes",
    "Extra_context": "Represents status: OK in content views such as a tables",
    color: 'var(--pf-v6-global--success-color--100)',
  },
  {
    "Style": "fas",
    "Name": "fa-clipboard-check",
    "React_name": "ClipboardCheckIcon",
    "Type": "Object",
    "Contextual_usage": "Represents orders or tasks",
  },
  {
    "Style": "far",
    "Name": "fa-clock",
    "React_name": "OutlinedClockIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents a time interval",
  },
  {
    "Style": "fas",
    "Name": "fa-code",
    "React_name": "CodeIcon",
    "Type": "Object",
    "Contextual_usage": "Represents code",
  },
  {
    "Style": "fas",
    "Name": "fa-code-branch",
    "React_name": "CodeBranchIcon",
    "Type": "Object",
    "Contextual_usage": "Represents code branch",
  },
  {
    "Style": "fas",
    "Name": "fa-cog",
    "React_name": "CogIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates availability of configurable settings",
    "Label": "Settings"
  },
  {
    "Style": "fas",
    "Name": "fa-columns",
    "React_name": "ColumnsIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to manage columns for a table view",
  },
  {
    "Style": "far",
    "Name": "fa-comments",
    "React_name": "OutlinedCommentsIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates availability of commenting",
  },
  {
    "Style": "fas",
    "Name": "fa-compress",
    "React_name": "CompressIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to compress an item. Should toggle with fa-expand",
  },
  {
    "Style": "fas",
    "Name": "fa-compress-arrows-alt",
    "React_name": "CompressArrowsAltIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to compress an item (alt concept). Should toggle with fa-expand-arrows-alt",
  },
  {
    "Style": "fas",
    "Name": "fa-copy",
    "React_name": "CopyIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the availability of a copy to clipboard function",
    "Label": "Copy"
  },
  {
    "Style": "pficon",
    "Name": "pficon-critical-risk",
    "React_name": "CriticalRiskIcon",
    "Type": "Status",
    "Contextual_usage": "Represents potential critical impact on a system or cluster",
  },
  {
    "Style": "fas",
    "Name": "fa-cube",
    "React_name": "CubeIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a container",
  },
  {
    "Style": "fas",
    "Name": "fa-cubes",
    "React_name": "CubesIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a Kubernetes pod(s)",
  },
  {
    "Style": "fas",
    "Name": "fa-database",
    "React_name": "DatabaseIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a database",
  },
  {
    "Style": "fas",
    "Name": "fa-desktop",
    "React_name": "DesktopIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a desktop, workstation or terminal",
  },
  {
    "Style": "fas",
    "Name": "fa-download",
    "React_name": "DownloadIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates a download function is available",
    "Label": "Download"
  },
  {
    "Style": "fas",
    "Name": "fa-ellipsis-v",
    "React_name": "EllipsisVIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates a contextual menu of actions or additional actions is available",
    "Label": "More options"
  },
  {
    "Style": "fas",
    "Name": "fa-exclamation-circle",
    "React_name": "ExclamationCircleIcon",
    "Type": "Status",
    "Contextual_usage": "Represents alert status: danger, major error or critical error",
    color: 'var(--pf-v6-global--danger-color--100)',
  },
  {
    "Style": "fas",
    "Name": "fa-exclamation-triangle",
    "React_name": "ExclamationTriangleIcon",
    "Type": "Status",
    "Contextual_usage": "Represents alert status: warning",
    color: 'var(--pf-v6-global--warning-color--100)',
  },
  {
    "Style": "fas",
    "Name": "fa-expand",
    "React_name": "ExpandIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to expand an item. Should toggle with fa-compress",
  },
  {
    "Style": "fas",
    "Name": "fa-expand-arrows-alt",
    "React_name": "ExpandArrowsAltIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to expand an item (alt concept). Should toggle with fa-compress-arrows-alt",
  },
  {
    "Style": "fas",
    "Name": "fa-external-link-alt",
    "React_name": "ExternalLinkAltIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the link navigates to an external site",
  },
  {
    "Style": "fas",
    "Name": "fa-eye",
    "React_name": "EyeIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the content of a component is currently hidden but can be revealed",
  },
  {
    "Style": "fas",
    "Name": "fa-eye-slash",
    "React_name": "EyeSlashIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the content of a component is revealed but can be hidden",
  },
  {
    "Style": "fas",
    "Name": "fa-file",
    "React_name": "FileIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents a file type",
  },
  {
    "Style": "fas",
    "Name": "fa-filter",
    "React_name": "FilterIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to filter search results or datasets",
  },
  {
    "Style": "fas",
    "Name": "fa-flag",
    "React_name": "FlagIcon",
    "Type": ["Object", "Action"],
    "Contextual_usage": "Represents a message.",
    "Extra_context": "Also indicates the ability to access a messages.",
  },
  {
    "Style": "fas",
    "Name": "fa-folder",
    "React_name": "FolderIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents a collapsed hierarchical group.",
    "Extra_context": "Indicates the ability to expand the group.",
  },
  {
    "Style": "fas",
    "Name": "fa-folder-open",
    "React_name": "FolderOpenIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents an expanded hierarchical group.",
    "Extra_context": "Indicates the ability to collapse the group.",
  },
  {
    "Style": "fas",
    "Name": "fa-grip-horizontal",
    "React_name": "GripHorizontalIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to move a vertically-oriented component via drag and drop",
  },
  {
    "Style": "fas",
    "Name": "fa-grip-vertical",
    "React_name": "GripVerticalIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to move a horizontally-oriented component via drag and drop",
  },
  {
    "Style": "fas",
    "Name": "fa-history",
    "React_name": "HistoryIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: restarting",
  },
  {
    "Style": "fas",
    "Name": "fa-undo",
    "React_name": "UndoIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to undo an a step in a historical log",
  },
  {
    "Style": "fas",
    "Name": "fa-hdd",
    "React_name": "OutlinedHddIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a single node or host",
  },
  {
    "Style": "fas",
    "Name": "fa-home",
    "React_name": "HomeIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates a link to a default/home page",
  },
  {
    "Style": "fas",
    "Name": "fa-info-circle",
    "React_name": "InfoCircleIcon",
    "Type": "Status",
    "Contextual_usage": "Represents alert status: information",
    color: 'var(--pf-v6-global--info-color--100)',
  },
  {
    "Style": "fas",
    "Name": "fa-key",
    "React_name": "KeyIcon",
    "Type": "Object",
    "Contextual_usage": "Represents an SSH key or similar security concepts",
  },
  {
    "Style": "fas",
    "Name": "fa-list",
    "React_name": "ListIcon",
    "Type": "View Type",
    "Contextual_usage": "Represents data view content in a list format.",
  },
  {
    "Style": "fas",
    "Name": "fa-lock",
    "React_name": "LockIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: locked",
  },
  {
    "Style": "fas",
    "Name": "fa-lock-open",
    "React_name": "LockOpenIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: unlocked",
  },
  {
    "Style": "fas",
    "Name": "fa-long-arrow-alt-down",
    "React_name": "LongArrowAltDownIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents the largest-to-smallest, highest-to-lowest or last-to-first (descending) sort order for any data type in a data table column. Clicking this will toggle the sort to ascending.",
  },
  {
    "Style": "fas",
    "Name": "fa-long-arrow-alt-up",
    "React_name": "LongArrowAltUpIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents the smallest-to-largest, lowest-to-highest or first-to-last (ascending) sort order for any data type in a data table column. Clicking this will toggle the sort to descending.",
  },
  {
    "Style": "fas",
    "Name": "fa-map-marker",
    "React_name": "MapMarkerIcon",
    "Type": "Framework",
    "Contextual_usage": "Represents a locale",
  },
  {
    "Style": "fas",
    "Name": "fa-memory",
    "React_name": "MemoryIcon",
    "Type": "Object",
    "Contextual_usage": "Represents the memory on a device",
  },
  {
    "Style": "fas",
    "Name": "fa-microchip",
    "React_name": "MicrochipIcon",
    "Type": "Object",
    "Contextual_usage": "Represents the CPU of a device",
  },
  {
    "Style": "fas",
    "Name": "fa-minus",
    "React_name": "MinusIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to remove an item",
  },
  {
    "Style": "fas",
    "Name": "fa-minus-circle",
    "React_name": "MinusCircleIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to remove an item (alt concept)",
  },
  {
    "Style": "fas",
    "Name": "fa-pause",
    "React_name": "PauseIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to pause. Should toggle with fa-play",
  },
  {
    "Style": "fas",
    "Name": "fa-pause-circle",
    "React_name": "PauseCircleIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: an interruption and/or stoppage of a process",
  },
  {
    "Style": "fas",
    "Name": "fa-pencil-alt",
    "React_name": "PencilAltIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to edit an item",
    "Label": "Edit"
  },
  {
    "Style": "fas",
    "Name": "fa-plus",
    "React_name": "PlusIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to add an item; not for creating completely new objects (see pficon-circle-add)",
  },
  {
    "Style": "fas",
    "Name": "fa-plus-circle",
    "React_name": "PlusCircleIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to create an item",
  },
  {
    "Style": "pficon",
    "Name": "pficon-add-circle-o",
    "React_name": "AddCircleOIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to create an item. Use this if there are many instances of this icon in a UI (data list, table, etc) to reduce visual noise.",
  },
  {
    "Style": "fas",
    "Name": "fa-power-off",
    "React_name": "PowerOffIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: powered on",
  },
  {
    "Style": "pficon",
    "Name": "pficon-off",
    "React_name": "OffIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: powered off",
  },
  {
    "Style": "pficon",
    "Name": "pficon-openshift",
    "React_name": "OpenshiftIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: OpenShift",
  },
  {
    "Style": "pficon",
    "Name": "pficon-openstack",
    "React_name": "OpenstackIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: OpenStack",
  },
  {
    "Style": "fas",
    "Name": "fa-play",
    "React_name": "PlayIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to start or resume. Should toggle with fa-pause",
  },
  {
    "Style": "fas",
    "Name": "fa-print",
    "React_name": "PrintIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the availability of a print function",
  },
  {
    "Style": "far",
    "Name": "fa-question-circle (outlined)",
    "React_name": "OutlinedQuestionCircleIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the availability of contextual help",
  },
  {
    "Style": "fas",
    "Name": "fa-question-circle",
    "React_name": "QuestionCircleIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the availability of a help system in the masthead",
  },
  {
    "Style": "fas",
    "Name": "fa-redo",
    "React_name": "RedoIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to refresh. Please use the animated spinner to indicate that something is “loading” or in the middle of processing",
  },
  {
    "Style": "fas",
    "Name": "fa-search",
    "React_name": "SearchIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates that that user may perform a search",
    "Label": "Search"
  },
  {
    "Style": "fas",
    "Name": "fa-search-minus",
    "React_name": "SearchMinusIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to zoom out",
    "Label": "Search minus"
  },
  {
    "Style": "fas",
    "Name": "fa-search-plus",
    "React_name": "SearchPlusIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to zoom in",
    "Label": "Search plus"
  },
  {
    "Style": "fas",
    "Name": "fa-share-square",
    "React_name": "ShareSquareIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to share via various methods with others",
  },
  {
    "Style": "fas",
    "Name": "fa-sort-amount-down",
    "React_name": "SortAmountDownIcon",
    "Type": "Action",
    "Contextual_usage": "Represents the largest-to-smallest, highest-to-lowest or last-to-first (descending) sort order for any data type.",
  },
  {
    "Style": "fas",
    "Name": "fa-sort-amount-down-alt",
    "React_name": "SortAmountDownAltIcon",
    "Type": "Action",
    "Contextual_usage": "Represents the smallest-to-largest, lowest-to-highest or first-to-last (ascending) sort order for any data type.",
    "Unicode": "f884"
  },
  {
    "Style": "fas",
    "Name": "fa-sync-alt",
    "React_name": "SyncAltIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the availability of a sync action",
    "Label": "Sync; Refresh; Running"
  },
  {
    "Style": "fas",
    "Name": "fa-tag",
    "React_name": "TagIcon",
    "Type": "Object",
    "Contextual_usage": "Indicates the abiltiy to access or create a set of tags",
  },
  {
    "Style": "fas",
    "Name": "fa-table",
    "React_name": "TableIcon",
    "Type": "View Type",
    "Contextual_usage": "Represents data view content in a table format",
  },
  {
    "Style": "fas",
    "Name": "fa-tachometer-alt",
    "React_name": "TachometerAltIcon",
    "Type": "View Type",
    "Contextual_usage": "Represents data view content in a dashboard",
  },
  {
    "Style": "pficon",
    "Name": "pficon-task",
    "React_name": "TaskIcon",
    "Type": "Framework, Object",
    "Contextual_usage": "Indicates the ability to open a task drawer. Also can represent tasks or activity.",
    "Label": "Tasks"
  },
  {
    "Style": "fas",
    "Name": "fa-th",
    "React_name": "ThIcon",
    "Type": "View Type",
    "Contextual_usage": "Represents data view content in a small card format",
  },
  {
    "Style": "fas",
    "Name": "fa-th-large",
    "React_name": "ThLargeIcon",
    "Type": "View Type",
    "Contextual_usage": "Represents data view content in a large card format",
  },
  {
    "Style": "fas",
    "Name": "fa-thumbtack",
    "React_name": "ThumbtackIcon",
    "Type": "Framework",
    "Contextual_usage": "Indicates the ability to pin an item",
  },
  {
    "Style": "fas",
    "Name": "fa-times",
    "React_name": "TimesIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to close a modal or other panel. Also indicates the ability to clear existing data, such as filter criteria or labels",
  },
  {
    "Style": "fas",
    "Name": "fa-times-circle",
    "React_name": "TimesCircleIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to close the about modal",
  },
  {
    "Style": "fas",
    "Name": "fa-trash",
    "React_name": "TrashIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to delete",
    "Label": "Delete"
  },
  {
    "Style": "fas",
    "Name": "fa-upload",
    "React_name": "UploadIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates an upload function is available",
  },
  {
    "Style": "fas",
    "Name": "fa-user",
    "React_name": "UserIcon",
    "Type": ["Framework","Object"],
    "Contextual_usage": "Represents a user (in a dataset, paired with a username).",
    "Extra_context": "Indicates the availability of a user profile (in the masthead, paired with a username).",
    },
  {
    "Style": "fas",
    "Name": "fa-users",
    "React_name": "UsersIcon",
    "Type": "Object",
    "Contextual_usage": "Represents multiple users, a user grouping or project",
  },
  {
    "Style": "far",
    "Name": "fa-window-restore",
    "React_name": "OutlinedWindowRestoreIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to open link in a new window",
  },
  {
    "Style": "fas",
    "Name": "fa-wrench",
    "React_name": "WrenchIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: in preparation for maintenance",
  },
  {
    "Style": "fab",
    "Name": "fa-github",
    "React_name": "GithubIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: GitHub",
  },
  {
    "Style": "fab",
    "Name": "fa-gitlab",
    "React_name": "GitlabIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: GitLab",
  },
  {
    "Style": "fab",
    "Name": "fa-google",
    "React_name": "GoogleIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Google",
  },
  {
    "Style": "fab",
    "Name": "fa-stack-overflow",
    "React_name": "StackOverflowIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Stack Overflow",
  },
  {
    "Style": "fab",
    "Name": "fa-facebook-square",
    "React_name": "FacebookSquareIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Facebook",
  },
  {
    "Style": "fab",
    "Name": "fa-twitter",
    "React_name": "TwitterIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Twitter",
  },
  {
    "Style": "fab",
    "Name": "fa-windows",
    "React_name": "WindowsIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Windows",
  },
  {
    "Style": "fab",
    "Name": "fa-linkedin",
    "React_name": "LinkedinIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: LinkedIn",
  },
  {
    "Style": "fab",
    "Name": "fa-linux",
    "React_name": "LinuxIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Linux",
  },
  {
    "Style": "fab",
    "Name": "fa-dropbox",
    "React_name": "DropboxIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Dropbox",
  },
  {
    "Style": "fab",
    "Name": "fa-drupal",
    "React_name": "DrupalIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Drupal",
  },
  {
    "Style": "fab",
    "Name": "fa-js",
    "React_name": "JsIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: js",
  },
  {
    "Style": "pficon",
    "Name": "pficon-asleep",
    "React_name": "AsleepIcon",
    "Type": "Status",
    "Contextual_usage": "Represents an item is asleep or in power suspended mode",
  },
  {
    "Style": "pficon",
    "Name": "pficon-automation",
    "React_name": "AutomationIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a process-automation object",
  },
  {
    "Style": "pficon",
    "Name": "pficon-blueprint",
    "React_name": "BlueprintIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a blueprint",
  },
  {
    "Style": "pficon",
    "Name": "pficon-build",
    "React_name": "BuildIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a build",
  },
  {
    "Style": "pficon",
    "Name": "pficon-builder-image",
    "React_name": "BuilderImageIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a builder image",
  },
  {
    "Style": "pficon",
    "Name": "pficon-bundle",
    "React_name": "BundleIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a package; used in Satellite, Cockpit, and Composer to indicate a generic package or rpm",
  },
  {
    "Style": "pficon",
    "Name": "pficon-catalog",
    "React_name": "CatalogIcon",
    "Type": "Object",
    "Contextual_usage": "Indicates the availability of a catalog or library",
  },
  {
    "Style": "pficon",
    "Name": "pficon-cloud-security",
    "React_name": "CloudSecurityIcon",
    "Type": "Object",
    "Contextual_usage": "Represents cloud security",
  },
  {
    "Style": "pficon",
    "Name": "pficon-cloud-tenant",
    "React_name": "CloudTenantIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a cloud tenant",
  },
  {
    "Style": "pficon",
    "Name": "pficon-cluster",
    "React_name": "ClusterIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a cluster or server",
  },
  {
    "Style": "pficon",
    "Name": "pficon-connected",
    "React_name": "ConnectedIcon",
    "Type": "Status",
    "Contextual_usage": "Represents an item's power is on and is “up”; this is a more active alternative to “pficon-on”",
  },
  {
    "Style": "pficon",
    "Name": "pficon-data-processor",
    "React_name": "DataProcessorIcon",
    "Type": "Status",
    "Contextual_usage": "Represents a data processor",
  },
  {
    "Style": "pficon",
    "Name": "pficon-data-sink",
    "React_name": "DataSinkIcon",
    "Type": "Status",
    "Contextual_usage": "Represents a data sink",
  },
  {
    "Style": "pficon",
    "Name": "pficon-data-source",
    "React_name": "DataSourceIcon",
    "Type": "Status",
    "Contextual_usage": "Represents a data source",
  },
  {
    "Style": "pficon",
    "Name": "pficon-degraded",
    "React_name": "DegradedIcon",
    "Type": "Status",
    "Contextual_usage": "Volume replication is degraded",
  },
  {
    "Style": "pficon",
    "Name": "pficon-disconnected",
    "React_name": "DisconnectedIcon",
    "Type": "Status",
    "Contextual_usage": "Represents an item's power is off and is “down”; this is a more active alternative to “pficon-off”",
  },
  {
    "Style": "pficon",
    "Name": "pficon-domain",
    "React_name": "DomainIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a domain",
  },
  {
    "Style": "pficon",
    "Name": "pficon-enhancement",
    "React_name": "EnhancementIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: enhancement advisory is present",
  },
  {
    "Style": "pficon",
    "Name": "pficon-enterprise",
    "React_name": "EnterpriseIcon",
    "Type": "Object",
    "Contextual_usage": "Represents an enterprise",
  },
  {
    "Style": "pficon",
    "Name": "pficon-export",
    "React_name": "ExportIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to export a file or other data",
    "Label": "Export"
  },
  {
    "Style": "pficon",
    "Name": "pficon-flavor",
    "React_name": "FlavorIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a flavor",
  },
  {
    "Style": "fas",
    "Name": "fa-image",
    "React_name": "ImageIcon",
    "Type": "Object",
    "Contextual_usage": "Represents an image",
  },
  {
    "Style": "pficon",
    "Name": "pficon-import",
    "React_name": "ImportIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to import a file or other data",
  },
  {
    "Style": "pficon",
    "Name": "pficon-in-progress",
    "React_name": "InProgressIcon",
    "Type": "Status",
    "Contextual_usage": "Represents running a determinite action",
  },
  {
    "Style": "pficon",
    "Name": "pficon-infrastructure",
    "React_name": "InfrastructureIcon",
    "Type": "Object",
    "Contextual_usage": "Represents an infrastructure",
  },
  {
    "Style": "pficon",
    "Name": "pficon-integration",
    "React_name": "IntegrationIcon",
    "Type": "Object",
    "Contextual_usage": "Represents an integration of two or more objects",
  },
  {
    "Style": "pficon",
    "Name": "pficon-migration",
    "React_name": "MigrationIcon",
    "Type": "Status",
    "Contextual_usage": "Represents an item such as a VM is currently migrating",
  },
  {
    "Style": "pficon",
    "Name": "pficon-middleware",
    "React_name": "MiddlewareIcon",
    "Type": "Object",
    "Contextual_usage": "Represents middleware",
  },
  {
    "Style": "pficon",
    "Name": "pficon-module",
    "React_name": "ModuleIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a module",
  },
  {
    "Style": "pficon",
    "Name": "pficon-monitoring",
    "React_name": "MonitoringIcon",
    "Type": "Object",
    "Contextual_usage": "Represents monitoring",
  },
  {
    "Style": "pficon",
    "Name": "pficon-multicluster",
    "React_name": "MulticlusterIcon",
    "Type": "Object",
    "Contextual_usage": "Indicates a multicluster object",
  },
  {
    "Style": "pficon",
    "Name": "pficon-network",
    "React_name": "NetworkIcon",
    "Type": "Object",
    "Contextual_usage": "Represents network",
  },
  {
    "Style": "pficon",
    "Name": "pficon-pficon-network-range",
    "React_name": "PficonNetworkRangeIcon",
    "Type": "Object",
    "Contextual_usage": "Represents network range",
  },
  {
    "Style": "pficon",
    "Name": "pficon-running",
    "React_name": "RunningIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: running",
  },
  {
    "Style": "pficon",
    "Name": "pficon-open-drawer-right",
    "React_name": "OpenDrawerRightIcon",
    "Type": "Action",
    "Contextual_usage": "Open or close a drawer",
  },
  {
    "Style": "pficon",
    "Name": "pficon-optimize",
    "React_name": "OptimizeIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to optimize an item or a process",
  },
  {
    "Style": "pficon",
    "Name": "pficon-package",
    "React_name": "PackageIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a package",
  },
  {
    "Style": "pficon",
    "Name": "pficon-pending",
    "React_name": "PendingIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: pending; currently waiting on contingencies",
  },
  {
    "Style": "pficon",
    "Name": "pficon-private",
    "React_name": "PrivateIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: private; cannot access with current credentials",
  },
  {
    "Style": "pficon",
    "Name": "pficon-port",
    "React_name": "PortIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a port or route",
  },
  {
    "Style": "pficon",
    "Name": "pficon-process-automation",
    "React_name": "ProcessAutomationIcon",
    "Type": "Object",
    "Contextual_usage": "Represents process automation",
  },
  {
    "Style": "pficon",
    "Name": "pficon-regions",
    "React_name": "RegionsIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a region",
  },
  {
    "Style": "pficon",
    "Name": "pficon-registry",
    "React_name": "RegistryIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a registry",
  },
  {
    "Style": "pficon",
    "Name": "pficon-replicator",
    "React_name": "ReplicatorIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a replicator",
  },
  {
    "Style": "pficon",
    "Name": "pficon-repository",
    "React_name": "RepositoryIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a repository",
  },
  {
    "Style": "pficon",
    "Name": "pficon-resource-pool",
    "React_name": "ResourcePoolIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a resource pool",
  },
  {
    "Style": "pficon",
    "Name": "pficon-resources-empty",
    "React_name": "ResourcesEmptyIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: is empty",
  },
  {
    "Style": "pficon",
    "Name": "pficon-resources-almost-empty",
    "React_name": "ResourcesAlmostEmptyIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: is almost empty",
  },
  {
    "Style": "pficon",
    "Name": "pficon-resources-almost-full",
    "React_name": "ResourcesAlmostFullIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: is almost full",
  },
  {
    "Style": "pficon",
    "Name": "pficon-resources-full",
    "React_name": "ResourcesFullIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: is full",
  },
  {
    "Style": "fas",
    "Name": "fa-route",
    "React_name": "RouteIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a route",
    "Unicode": "f4d7"
  },
  {
    "Style": "pficon",
    "Name": "pficon-pficon-satellite",
    "React_name": "PficonSatelliteIcon",
    "Type": "Brands",
    "Contextual_usage": "Represents brand: Satellite",
  },
  {
    "Style": "pficon",
    "Name": "pficon-save",
    "React_name": "SaveIcon",
    "Type": "Action",
    "Contextual_usage": "Indicates the ability to save a file or other object",
  },
  {
    "Style": "pficon",
    "Name": "pficon-security",
    "React_name": "SecurityIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: security advisory is present",
  },
  {
    "Style": "pficon",
    "Name": "pficon-server-group",
    "React_name": "ServerGroupIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a server group",
  },
  {
    "Style": "pficon",
    "Name": "pficon-service",
    "React_name": "ServiceIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a Kubernetes service",
  },
  {
    "Style": "pficon",
    "Name": "pficon-services",
    "React_name": "ServicesIcon",
    "Type": "Object",
    "Contextual_usage": "Represents services",
  },
  {
    "Style": "pficon",
    "Name": "pficon-service-catalog",
    "React_name": "ServiceCatalogIcon",
    "Type": "Object",
    "Contextual_usage": "Indicates availability of a catalog/library to browse",
  },
  {
    "Style": "pficon",
    "Name": "pficon-storage-domain",
    "React_name": "StorageDomainIcon",
    "Type": "Object",
    "Contextual_usage": "Indicates a storage domain",
  },
  {
    "Style": "pficon",
    "Name": "pficon-pficon-template",
    "React_name": "PficonTemplateIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a template; includes contents or instructions used to generate one or more instances of a final output",
  },
  {
    "Style": "pficon",
    "Name": "pficon-tenant",
    "React_name": "TenantIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a tenant",
  },
  {
    "Style": "pficon",
    "Name": "pficon-topology",
    "React_name": "TopologyIcon",
    "Type": "View type",
    "Contextual_usage": "Represents data view content in a topology format",
  },
  {
    "Style": "pficon",
    "Name": "pficon-trend-down",
    "React_name": "TrendDownIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: downward trend",
  },
  {
    "Style": "pficon",
    "Name": "pficon-trend-up",
    "React_name": "TrendUpIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: upward trend",
  },
  {
    "Style": "pficon",
    "Name": "pficon-unknown",
    "React_name": "UnknownIcon",
    "Type": "Status",
    "Contextual_usage": "Represents status: unknown",
  },
  {
    "Style": "pficon",
    "Name": "pficon-pficon-vcenter",
    "React_name": "PficonVcenterIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a vcenter",
  },
  {
    "Style": "pficon",
    "Name": "pficon-virtual-machine",
    "React_name": "VirtualMachineIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a virtual machine",
  },
  {
    "Style": "pficon",
    "Name": "pficon-volume",
    "React_name": "VolumeIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a volume",
  },
  {
    "Style": "pficon",
    "Name": "pficon-zone",
    "React_name": "ZoneIcon",
    "Type": "Object",
    "Contextual_usage": "Represents a zone; a grouping of servers based on geographic location, network location, or function",
  }
]
